import './style.css'
import "./globals.css";
import { Inter } from "next/font/google";

import { Footer, CustomCursor } from "./components";
import 'typeface-oswald';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
 
      </head>

      <body className={inter.className}>
        {children}
        <CustomCursor />
      </body>
    </html>
  );
}
